---

- name: check db insert works
  hosts: all
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml

  collections:
    - community.mysql

  vars:

  tasks:
    - name: download pem key to instance from AWS
      get_url:
        url: https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem
        dest: "{{aws_ca_key}}"


    - name: insert key into my.cnf file
      ini_file: dest=/home/ec2-user/.my.cnf section=client option=ssl-ca value="{{aws_ca_key}}"


    - name: insert mesoform.com users into db
      become: False
      mysql_query:
        login_db: "{{databasename}}"
        login_host: "{{databasehost}}"
        login_port: "{{databaseport}}"
        login_user: "{{databaseuser}}"
        login_password: "{{databasepassword}}"
        query:
          - INSERT INTO passwd2 (id,crypt,clear,name,uid,gid,home,maildir,defaultdelivery,quota,options) VALUES("{{item.key}}", SHA2("{{item.value.password}}", 256), "" , "{{item.value.fullname}}", "476", "2003" , "{{email_root}}/{{ item.key.split('@')[1] }}/{{ item.key.split('@')[0] }}" , "{{email_root}}/{{ item.key.split('@')[1] }}/{{ item.key.split('@')[0] }}" , "", "", "")
      loop: "{{ lookup('dict', users) }}"
      when: item.key.split("@")[1] == "mesoform.com"

    - name: insert mesoform.com users into db
      become: False
      mysql_query:
        login_db: "{{databasename}}"
        login_host: "{{databasehost}}"
        login_port: "{{databaseport}}"
        login_user: "{{databaseuser}}"
        login_password: "{{databasepassword}}"
        query:
          - INSERT INTO passwd2 (id,crypt,clear,name,uid,gid,home,maildir,defaultdelivery,quota,options) VALUES("{{item.key}}", SHA2("{{item.value.password}}", 256), "" , "{{item.value.fullname}}", "476", "2002" , "{{email_root}}/{{ item.key.split('@')[1] }}/{{ item.key.split('@')[0] }}" , "{{email_root}}/{{ item.key.split('@')[1] }}/{{ item.key.split('@')[0] }}" , "", "", "")
      loop: "{{ lookup('dict', users) }}"
      when: item.key.split("@")[1] == "gbmail.com"


#    - name: insert gbmail.me users into db
#      mysql_query:
#        name: saltydb
#        login_host: saltydb3.cljjx3jkbvhq.eu-west-2.rds.amazonaws.com
#        login_port: 3306
#        login_user: "{{databaseuser}}"
#        login_password: "{{databasepassword}}"
#        identifiers:
#          id: "{{item.key}}"
#        values:
#          crypt: "{{item.value.password }}"
#          clear: ""
#          name: "{{item.value.fullname}}"
#          uid: 476
#          gid: 2002
#          home: "{{email_root}}/{{ item.key.split('@')[1] }}/{{ item.key.split('@')[0] }}"
#          maildir: "{{email_root}}/{{ item.key.split('@')[1] }}/{{ item.key.split('@')[0] }}"
#          defaultdelivery: ""
#          quota: ""
#          options: ""
#      loop: "{{ lookup('dict', users) }}"
#      when: item.key.split("@")[1] == "gbmail.com"








### from trello
###  users stored in this file roles/email.gbweb.net/vars/users.yml in the format username:password
### create the sql insert variables colums id , crypt, clear, name,muid, gid, home, maildir, defaultdeliver, quota, options

#- name: split variables to create
#  hosts: all
#  vars:
#    newusers: {}
#    users:
#      salty@mesoform.com:
#        password: password
#        fullname: "saltsus millott"
#      gaz@mesoform.com:
#        password: password2
#        fullname: "gareth brown"
#        password: password2
#
#      test@gbmail.com: password3
#  tasks:
#    - name: get local domain part
#      set_fact:
#        localpart: "{{ key.split('@')[0] }}"
#      loop: "{{ users | dict2items }}"
#    - debug:
#        var: localpart





#    - name: gid for each dict item

#    - name: home for each dict item
